//
// Created by cempl on 13.12.22.
//

#ifndef CPP_XPX_STORAGE_USER_APP_DRIVEMODIFICATIONEVENT_H
#define CPP_XPX_STORAGE_USER_APP_DRIVEMODIFICATIONEVENT_H


class DriveModificationEvent {

};


#endif //CPP_XPX_STORAGE_USER_APP_DRIVEMODIFICATIONEVENT_H
