//
// Created by cempl on 13.12.22.
//

#ifndef CPP_XPX_STORAGE_USER_APP_DRIVEMODIFICATIONTRANSITION_H
#define CPP_XPX_STORAGE_USER_APP_DRIVEMODIFICATIONTRANSITION_H


class DriveModificationTransition {

};


#endif //CPP_XPX_STORAGE_USER_APP_DRIVEMODIFICATIONTRANSITION_H
